kind: Cluster
name: $CLUSTER_NAME
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "$POD_CIDR"
  serviceSubnet: "$SERVICE_CIDR"
  disableDefaultCNI: true
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker